<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CreditTopUp.Domain\CreditTopUp.Domain.csproj" />
    <ProjectReference Include="..\CreditTopUp.Infra\CreditTopUp.Infra.csproj" />
  </ItemGroup>

</Project>
